services:
    tests:
        build:
            context: .
            dockerfile: Dockerfile

        networks:
            - testnet
        volumes:
            - ./tests:/tests
        command: ['npm', 'run', 'test']

networks:
    testnet:
        driver: bridge
